baseURL: "https://jacopouggeri.github.io" 
title: Jacopo Uggeri
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter:

taxonomies:
    tag: tags

menu:
    main:
        #- name: Papers
          #url: /papers/
          #weight: 1
        #- name: Courses
          #url: /courses/
          #weight: 2
        #- name: Design
          #url: /design/
          #weight: 3
        - name: Posts
          url: /posts/
          weight: 1
        - name: Projects
          url: /projects/
          weight: 1
        - name: Tags
          url: /tags/
          weight: 2     
        #- name: Newsletter
          #url: https://pmichaillat.substack.com
          #weight: 4

params:
    description: "Enthusiastic Theoretical Physics student. My current research interest is in quantum gravity and black hole physics. Curious about learning languages, game design and the graphical and visual aspect of science communication."
    author: Jacopo Uggeri
    googleAnalyticsID:
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jacopo Uggeri
          subtitle: "Enthusiastic Theoretical Physics student. My current research interest is in quantum gravity and black hole physics. Curious about learning languages, game design and the graphical and visual aspect of science communication."
          imageUrl: "/profile.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jacopo Uggeri
          buttons:
            - name: Posts
              url: /posts/
            - name: Projects
              url: /projects/
            #- name: Papers
              #url: /papers/
            #- name: Courses
              #url: /courses/
            #- name: Design
              #url: /design/
            #- name: Newsletter
              #url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:jacopo.uggeri@gmail.com
        - name: Location
          url: /location/
        - name: OrcID
          url: https://orcid.org/0009-0001-1469-5566
        - name: ResearchGate
          url: https://www.researchgate.net/profile/Jacopo_Uggeri
        - name: YouTube
          url: https://www.youtube.com/@jacopouggeri
        - name: GitHub
          url: https://github.com/jacopouggeri?tab=repositories
        - name: LinkedIn
          url: https://linkedin.com/in/jacopo-uggeri-191605198

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Jacopo Uggeri"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
