baseURL: 'https://jacopouggeri.github.io/'
languageCode: 'en-us'
title: 'Jacopo Uggeri'
theme: 'showfolio'

params:
  name: "Jacopo Uggeri"
  description: "Enthusiastic Theoretical Physics student."
  author: "Jacopo Uggeri"
  authorEmail: "jacopo.uggeri@gmail.com"
  authorResume: "/a4cv/"
  authorImage: "profile.png"
  autoDarkMode: true
  copyright: "Copyright © 2023 - Jacopo Uggeri · All rights reserved"
  favicon: "favicon.ico"
  homepage:
    title: "Hey 👋 I'm Jacopo, a"
    tagline: "Theoretical Physics Student"
    description: "My current research interest is in gravity beyond General Relativity and black hole physics. I'm curious about learning languages, coding and the graphical and visual aspect of science communication."
    contact: mailto:jacopo.uggeri@gmail.com"
    social:
      linktree: https://linktr.ee/jacopouggeri
      linkedin: https://linkedin.com/in/jacopouggeri000
      github: https://github.com/jacopouggeri?tab=repositories
      youtube: https://www.youtube.com/@jacopouggeri
      orcid: https://orcid.org/0009-0001-1469-5566

build:
  writeStats: true

markup:
  highlight:
    style: "dracula"
