baseURL = 'https://jacopouggeri.github.io/'
languageCode = 'en-us'
title = 'Jacopo Uggeri'
theme = 'showfolio'

[params]
  name = "Jacopo Uggeri"
  description = "Modern portfolio theme for your Hugo site."
  author = "Jacopo Uggeri"
  authorEmail = "jacopo.uggeri@gmail.com"
  authorImage = "profile.png"
  autoDarkMode = true

  copyright = "Copyright © 2023 - Jacopo Uggeri · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey 👋 I'm Jacopo Uggeri"
  tagline = "Theoretical Physics Student"
  description = "Develop functional user interfaces and provide a valuable experience to customers."
  contact = "https://twitter.com/"

[params.homepage.social]
  twitter =
  linkedin = "https://linkedin.com/in/jacopouggeri000"
  github = "https://github.com/jacopouggeri"
  medium = 
  reddit = 
  dribbble = 

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"